### ISSUE TITLE
[1.7.10]: Todo

### ISSUE THREAD

**Issue by quentin452** [quentin452/Multithreadingandtweaks#18]
### Todo

- [ ] make a better config that being ressetted when updated / make categories
- [ ] fix when enabling multithreading on Improved Noise that make worldgen height bug
- [ ] Fix a large bottleneck caused by updateTask(caused by pathfinding) from MixinEntityAIAttackOnCollide /EntityAIAttackOnCollide class , profiler : [link](https://spark.lucko.me/rrH2v5SFYn) [download](https://mega.nz/file/zs1CnTDL#aMEak_7TpuffcS50yUmv3o4QN6wVgn1AE7IJlAPEp5Y)
- [ ] Fix a large bottleneck caused by collisions when there are alot of entities
